import { useState, type FormEvent } from 'react'
import { BellRing, Building2, Save, SlidersHorizontal } from 'lucide-react'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { Input } from '../../components/Input'

function Switch({ enabled, onClick, label, description }: { enabled: boolean; onClick: () => void; label: string; description: string }) {
  return <div className="flex items-center justify-between gap-5 py-4"><div><p className="text-sm font-semibold text-ink">{label}</p><p className="mt-1 text-sm text-muted">{description}</p></div><button type="button" onClick={onClick} aria-pressed={enabled} className={`relative h-6 w-11 shrink-0 rounded-full transition ${enabled ? 'bg-brand' : 'bg-slate-200'}`}><span className={`absolute top-1 size-4 rounded-full bg-white shadow-sm transition ${enabled ? 'left-6' : 'left-1'}`} /></button></div>
}

export function RestaurantSettings() {
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [deliveryNotifications, setDeliveryNotifications] = useState(true)
  const [weeklyReport, setWeeklyReport] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setSaved(false); window.setTimeout(() => { setSaving(false); setSaved(true) }, 500) }
  return <div className="mx-auto max-w-4xl space-y-6"><div><p className="text-sm text-muted">Preferências da operação</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-ink">Configurações</h2></div><Card className="p-6 sm:p-7"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-orange-50 text-brand"><Building2 size={20} /></span><div><p className="font-bold text-ink">Dados do restaurante</p><p className="mt-1 text-sm text-muted">Informações exibidas aos motoboys parceiros.</p></div></div><form onSubmit={submit} className="mt-7 space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Input id="restaurant" label="Nome do restaurante" defaultValue="Sabor & Cia" required /><Input id="phone" label="Telefone" defaultValue="(11) 3333-4455" required /></div><Input id="address" label="Endereço de coleta padrão" defaultValue="Av. Paulista, 1000 - Bela Vista" required />{saved && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Configurações salvas com sucesso.</p>}<Button type="submit" disabled={saving}>{saving ? 'Salvando...' : <><Save size={17} />Salvar alterações</>}</Button></form></Card><Card className="p-6 sm:p-7"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-orange-50 text-brand"><BellRing size={20} /></span><div><p className="font-bold text-ink">Notificações</p><p className="mt-1 text-sm text-muted">Escolha como deseja acompanhar as entregas.</p></div></div><div className="mt-5 divide-y divide-slate-100"><Switch enabled={deliveryNotifications} onClick={() => setDeliveryNotifications((value) => !value)} label="Atualizações de entrega" description="Receba avisos quando o status de um pedido mudar." /><Switch enabled={weeklyReport} onClick={() => setWeeklyReport((value) => !value)} label="Relatório semanal" description="Receba um resumo de custos e entregas por e-mail." /></div></Card><Card className="p-6 sm:p-7"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-orange-50 text-brand"><SlidersHorizontal size={20} /></span><div><p className="font-bold text-ink">Preferências de entrega</p><p className="mt-1 text-sm text-muted">Defina regras padrão para suas solicitações.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Input id="radius" label="Raio de busca de motoboys" defaultValue="5 km" /><Input id="average" label="Valor médio por entrega" defaultValue="R$ 12,00" /></div></Card></div>
}
