import { ArrowLeft, Bike, Clock3, MapPin, Navigation, Store, Timer, Wallet } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { StatusBadge } from '../../components/StatusBadge'
import { deliveryMock } from '../../data/deliveriesMock'

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })

export function DeliveryRequest() {
  const navigate = useNavigate()
  return <div className="mx-auto max-w-5xl"><button type="button" onClick={() => navigate('/motoboy/dashboard')} className="mb-6 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500 hover:text-ink"><ArrowLeft size={17} />Voltar ao dashboard</button>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><Card className="overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-100 px-6 py-6"><div><div className="flex items-center gap-2"><StatusBadge status="waiting">Nova solicitação</StatusBadge><span className="inline-flex items-center gap-1 text-xs font-medium text-amber-700"><Timer size={14} />Expira em 01:42</span></div><h2 className="mt-4 text-2xl font-bold tracking-tight text-ink">Entrega para {deliveryMock.customer}</h2><p className="mt-1 text-sm text-muted">Pedido {deliveryMock.id} · recebido agora</p></div><p className="text-2xl font-bold tracking-tight text-brand">{money.format(deliveryMock.value)}</p></div>
      <div className="p-6"><div className="relative space-y-7 before:absolute before:bottom-6 before:left-[18px] before:top-7 before:w-px before:bg-orange-200"><div className="relative flex gap-4"><span className="z-10 grid size-9 shrink-0 place-items-center rounded-full bg-brand text-white"><Store size={17} /></span><div><p className="text-sm font-semibold text-ink">Retirar no restaurante</p><p className="mt-1 text-sm text-muted">{deliveryMock.restaurant}</p><p className="mt-1 text-sm text-slate-500">{deliveryMock.pickupAddress}</p></div></div><div className="relative flex gap-4"><span className="z-10 grid size-9 shrink-0 place-items-center rounded-full bg-ink text-white"><MapPin size={17} /></span><div><p className="text-sm font-semibold text-ink">Entregar ao cliente</p><p className="mt-1 text-sm text-muted">{deliveryMock.customer}</p><p className="mt-1 text-sm text-slate-500">{deliveryMock.deliveryAddress}</p></div></div></div>
        <div className="mt-8 flex flex-col-reverse gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={() => navigate('/motoboy/dashboard')}>Recusar</Button><Button onClick={() => navigate('/motoboy/delivery')}>Aceitar entrega <Navigation size={17} /></Button></div>
      </div></Card>
      <div className="space-y-4"><Card className="p-5"><p className="text-sm font-bold text-ink">Detalhes da corrida</p><div className="mt-5 space-y-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-orange-50 text-brand"><Bike size={17} /></span><div><p className="text-xs text-muted">Distância total</p><p className="text-sm font-semibold text-ink">{deliveryMock.distance}</p></div></div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-orange-50 text-brand"><Clock3 size={17} /></span><div><p className="text-xs text-muted">Tempo estimado</p><p className="text-sm font-semibold text-ink">{deliveryMock.estimatedTime}</p></div></div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-orange-50 text-brand"><Wallet size={17} /></span><div><p className="text-xs text-muted">Você recebe</p><p className="text-sm font-semibold text-emerald-600">{money.format(deliveryMock.value)}</p></div></div></div></Card><p className="px-2 text-xs leading-5 text-slate-400">Ao aceitar, você confirma que está disponível para realizar esta entrega.</p></div>
    </div></div>
}
